dependencies:
  - name: jsonpath.js
    source: https://raw.githubusercontent.com/kromain/qml-utils/e4cf5e0a0603d5861451929cb4cb005f117aefa4/JSONListModel/jsonpath.js

  - name: JSONListModel.qml
    source: https://raw.githubusercontent.com/kromain/qml-utils/e4cf5e0a0603d5861451929cb4cb005f117aefa4/JSONListModel/JSONListModel.qml

imports:
  - QtQuick 2.11
  - QtQuick.Layouts 1.11
  - QtQuick.Controls 2.4
  - QtQuick.Window 2.11
  - QtMultimedia 5.11
root:
  type: ApplicationWindow
  public:
    - name: server
      type: string
      value: https://airstream.apps.gammazeta.net

    - name: path
      type: string
      value: ""

  components:
    - type: JSONListView
      id: folders
      properties:
        source: "{ root.server + '/api/folders' }"

modules:
  - name: Ticker
    imports:
      - QtQuick 2.11
    definition:
      type: Timer
      properties:
        repeat: true
        running: true

  - name: FitText
    imports:
      - QtQuick 2.11
    definition:
      type: Text
      properties:
        width: "@parent.width"
        height: "@parent.height"
        fontSizeMode: "@Text.Fit"
        font.pixelSize: "100vmax"
        minimumPixelSize: "1vmin"
        color: "black"
        horizontalAlignment: "@Text.AlignHCenter"
        verticalAlignment: "@Text.AlignVCenter"

  - name: FolderItem
    imports:
      - QtQuick 2.11
    definition:
      type: Rectangle
      properties:
        color: red
        width: 100vw
        height: 10vh
      components:
        - type: FitText
          fill: true
          properties:
            text: "{ model.properties.title || model.path || '(empty)' }"

  - name: JSONListView
    imports:
      - QtQuick 2.11
    definition:
      type: Item
      id: view
      fill: true
      public:
        - name: source

      components:
        - type: JSONListModel
          id: data
          properties:
            source: "@view.source"

        - type: ListView
          fill: true
          properties:
            model: "@data.model"
            delegate: "@FolderItem{}"
